import mongoose from "mongoose";

const groupSchema = new mongoose.Schema(
  {
    Group: { type: String, required: false },
    Server: { type: Number, required: false },
    PermissionsFlags: { type: Number, required: false },
    AuthMode: { type: Number, required: false },
    AuthPasswordMin: { type: Number, required: false },
    AuthOTPMode: { type: Number, required: false },
    Company: { type: String, required: false },
    CompanyPage: { type: String, default: "" },
    CompanyEmail: { type: String, default: "" },
    CompanySupportPage: { type: String, default: "" },
    CompanySupportEmail: { type: String, default: "" },
    CompanyCatalog: { type: String, default: "" },
    CompanyDepositURL: { type: String, default: "" },
    CompanyWithdrawalURL: { type: String, default: "" },
    Currency: { type: String, required: false },
    CurrencyDigits: { type: Number, required: false },
    ReportsMode: { type: Number, default: 0 },
    ReportsFlags: { type: Number, default: 0 },
    ReportsEmail: { type: String, default: "" },
    NewsMode: { type: Number, default: 2 },
    NewsCategory: { type: String, default: "" },
    NewsLangs: { type: [String], default: [] },
    MailMode: { type: Number, default: 1 },
    TradeFlags: { type: Number, required: false },
    TradeTransferMode: { type: Number, default: 0 },
    TradeInterestrate: { type: Number, default: 0 },
    TradeVirtualCredit: { type: Number, default: 0 },
    MarginMode: { type: Number, required: false },
    MarginFlags: { type: Number, default: 0 },
    MarginSOMode: { type: Number, default: 0 },
    MarginFreeMode: { type: Number, default: 1 },
    MarginCall: { type: Number, default: 100.0 },
    MarginStopOut: { type: Number, default: 30.0 },
    MarginFreeProfitMode: { type: Number, default: 0 },
    MarginLeverageProfile: { type: String, default: "" },
    DemoLeverage: { type: Number, default: 400 },
    DemoDeposit: { type: Number, default: 0 },
    DemoTradesClean: { type: Number, default: 90 },
    LimitHistory: { type: Number, default: 0 },
    LimitOrders: { type: Number, default: 0 },
    LimitSymbols: { type: Number, default: 0 },
    LimitPositions: { type: Number, default: 0 },
    LimitPositionsVolume: { type: Number, default: 0 },
    WhiteLabel: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
    },
    Commissions: { type: [Object], default: [] },
    Symbols: {
      type: [
        {
          Path: { type: String, required: false },
          TradeMode: { type: String, default: "default" },
          ExecMode: { type: String, default: "default" },
          FillFlags: { type: String, default: "default" },
          ExpirFlags: { type: String, default: "default" },
          OrderFlags: { type: String, default: "default" },
          SpreadDiff: { type: String, default: 0 },
          SpreadDiffBalance: { type: String, default: 0 },
          StopsLevel: { type: String, default: 0 },
          FreezeLevel: { type: String, default: 0 },
          VolumeMin: { type: String, default: 0 },
          VolumeMinExt: { type: String, default: 0 },
          VolumeMax: { type: String, default: 0 },
          VolumeMaxExt: { type: String, default: 0 },
          VolumeStep: { type: String, default: 0 },
          VolumeStepExt: { type: String, default: 0 },
          VolumeLimit: { type: String, default: 0 },
          VolumeLimitExt: { type: String, default: 0 },
          MarginFlags: { type: String, default: 0 },
          MarginInitial: { type: String, default: 0 },
          MarginMaintenance: { type: String, default: 0 },
          MarginInitialBuy: { type: String, default: 0 },
          MarginInitialSell: { type: String, default: 0 },
          MarginInitialBuyLimit: { type: String, default: 0 },
          MarginInitialSellLimit: { type: String, default: 0 },
          MarginInitialBuyStop: { type: String, default: 0 },
          MarginInitialSellStop: { type: String, default: 0 },
          MarginInitialBuyStopLimit: { type: String, default: 0 },
          MarginInitialSellStopLimit: { type: String, default: 0 },
          MarginMaintenanceBuy: { type: String, default: 0 },
          MarginMaintenanceSell: { type: String, default: 0 },
          MarginMaintenanceBuyLimit: { type: String, default: 0 },
          MarginMaintenanceSellLimit: { type: String, default: 0 },
          MarginMaintenanceBuyStop: { type: String, default: 0 },
          MarginMaintenanceSellStop: { type: String, default: 0 },
          MarginMaintenanceBuyStopLimit: { type: String, default: 0 },
          MarginMaintenanceSellStopLimit: { type: String, default: 0 },
          MarginLiquidity: { type: String, default: 0 },
          MarginHedged: { type: String, default: 0 },
          MarginCurrency: { type: String, default: "" },
          SwapMode: { type: String, default: 0 },
          SwapLong: { type: String, default: 0 },
          SwapShort: { type: String, default: 0 },
          Swap3Day: { type: String, default: 0 },
          SwapFlags: { type: String, default: 0 },
          SwapYearDay: { type: String, default: 0 },
          SwapRateSunday: { type: String, default: 0 },
          SwapRateMonday: { type: String, default: 0 },
          SwapRateTuesday: { type: String, default: 0 },
          SwapRateWednesday: { type: String, default: 0 },
          SwapRateThursday: { type: String, default: 0 },
          SwapRateFriday: { type: String, default: 0 },
          SwapRateSaturday: { type: String, default: 0 },
          REFlags: { type: String, default: 0 },
          RETimeout: { type: String, default: 0 },
          IEFlags: { type: String, default: 0 },
          IECheckMode: { type: String, default: 0 },
          IETimeout: { type: String, default: 0 },
          IESlipProfit: { type: String, default: 0 },
          IESlipLosing: { type: String, default: 0 },
          IEVolumeMax: { type: String, default: 0 },
          IEVolumeMaxExt: { type: String, default: 0 },
          PermissionsFlags: { type: Number, default: 1 },
          PermissionsBookdepth: { type: Number, default: 0 },
        },
      ],
      default: [],
    },
    ManagerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "WhiteLabel",
    },
    ManagerType: {
      type: String,
      default: "real",
    },
    GroupName: {
      type: String,
      default: "",
    },
    MinimumDepositeLimit: {
      type: Number,
      default: 0,
    },
    range: {
      rangeStart: {
        type: Number,
        default: null,
      },
      rangeEnd: {
        type: Number,
        default: null,
      },
    },
    Spread: { type: Number, default: 0 },
    Commission: { type: Number, default: 0 },
    Description: {
      type: String,
      default: "Most popular! A great account for all types of traders",
    },
    Status: { type: Boolean, default: true },
    IsPopular: { type: Boolean, default: false },
    SortedPosition: { type: Number, default: 1 },
    LinkedGroupIds: {
      type: [{ type: mongoose.Schema.Types.ObjectId, ref: "ForexGroups" }],
      default: [],
    },
    LinkedGroups: { type: [String], default: [] },
  },
  {
    collection: "ForexGroups",
  }
);

export default mongoose.model("ForexGroups", groupSchema);
