import mongoose from "mongoose";

const groupSchema = new mongoose.Schema(
  {
    group: { type: String, required: false },
    groupName: { type: String, default: "", required: false },
    server: { type: Number, required: false },
    permissionsFlags: { type: Number, required: false },
    authMode: { type: Number, required: false },
    authPasswordMin: { type: Number, required: false },
    authOTPMode: { type: Number, required: false },
    company: { type: String, required: false },
    companyPage: { type: String, default: "" },
    companyEmail: { type: String, default: "" },
    companySupportPage: { type: String, default: "" },
    companySupportEmail: { type: String, default: "" },
    companyCatalog: { type: String, default: "" },
    companyDepositURL: { type: String, default: "" },
    companyWithdrawalURL: { type: String, default: "" },
    currency: { type: String, required: false },
    currencyDigits: { type: Number, required: false },
    reportsMode: { type: Number, default: 0 },
    reportsFlags: { type: Number, default: 0 },
    reportsEmail: { type: String, default: "" },
    newsMode: { type: Number, default: 2 },
    newsCategory: { type: String, default: "" },
    newsLangs: { type: [String], default: [] },
    mailMode: { type: Number, default: 1 },
    tradeFlags: { type: Number, required: false },
    tradeTransferMode: { type: Number, default: 0 },
    tradeInterestrate: { type: Number, default: 0 },
    tradeVirtualCredit: { type: Number, default: 0 },
    marginMode: { type: Number, required: false },
    marginFlags: { type: Number, default: 0 },
    marginSOMode: { type: Number, default: 0 },
    marginFreeMode: { type: Number, default: 1 },
    marginCall: { type: Number, default: 100.0 },
    marginStopOut: { type: Number, default: 30.0 },
    marginFreeProfitMode: { type: Number, default: 0 },
    marginLeverageProfile: { type: String, default: "" },
    demoLeverage: { type: Number, default: 400 },
    demoDeposit: { type: Number, default: 0 },
    demoTradesClean: { type: Number, default: 90 },
    limitHistory: { type: Number, default: 0 },
    limitOrders: { type: Number, default: 0 },
    limitSymbols: { type: Number, default: 0 },
    limitPositions: { type: Number, default: 0 },
    limitPositionsVolume: { type: Number, default: 0 },
    whiteLabel: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
    },
    commissions: { type: [Object], default: [] },
    symbols: {
      type: [
        {
          path: { type: String, required: false },
          tradeMode: { type: String, default: "default" },
          execMode: { type: String, default: "default" },
          fillFlags: { type: String, default: "default" },
          expirFlags: { type: String, default: "default" },
          orderFlags: { type: String, default: "default" },
          spreadDiff: { type: String, default: 0 },
          spreadDiffBalance: { type: String, default: 0 },
          stopsLevel: { type: String, default: 0 },
          freezeLevel: { type: String, default: 0 },
          volumeMin: { type: String, default: 0 },
          volumeMinExt: { type: String, default: 0 },
          volumeMax: { type: String, default: 0 },
          volumeMaxExt: { type: String, default: 0 },
          volumeStep: { type: String, default: 0 },
          volumeStepExt: { type: String, default: 0 },
          volumeLimit: { type: String, default: 0 },
          volumeLimitExt: { type: String, default: 0 },
          marginFlags: { type: String, default: 0 },
          marginInitial: { type: String, default: 0 },
          marginMaintenance: { type: String, default: 0 },
          marginInitialBuy: { type: String, default: 0 },
          marginInitialSell: { type: String, default: 0 },
          marginInitialBuyLimit: { type: String, default: 0 },
          marginInitialSellLimit: { type: String, default: 0 },
          marginInitialBuyStop: { type: String, default: 0 },
          marginInitialSellStop: { type: String, default: 0 },
          marginInitialBuyStopLimit: { type: String, default: 0 },
          marginInitialSellStopLimit: { type: String, default: 0 },
          marginMaintenanceBuy: { type: String, default: 0 },
          marginMaintenanceSell: { type: String, default: 0 },
          marginMaintenanceBuyLimit: { type: String, default: 0 },
          marginMaintenanceSellLimit: { type: String, default: 0 },
          marginLiquidity: { type: String, default: 0},
          marginHedged: { type: String, default: 0 },
          marginCurrency: { type: String, default: "" },
          swapMode: { type: String, default: 0 },
          swapLong: { type: String, default: 0 },
          swapShort: { type: String, default: 0 },
          swap3Day: { type: String, default: 0 },
          swapFlags: { type: String, default: 0 },
          swapYearDay: { type: String, default: 0 },
          swapRateSunday: { type: String, default: 0 },
          swapRateMonday: { type: String, default: 0 },
          swapRateTuesday: { type: String, default: 0 },
          swapRateWednesday: { type: String, default: 0 },
          swapRateThursday: { type: String, default: 0 },
          swapRateFriday: { type: String, default: 0 },
          swapRateSaturday: { type: String, default: 0 },
          reFlags: { type: String, default: 0 },
          reTimeout: { type: String, default: 0 },
          reFlags: { type: String, default: 0 },
          ieCheckMode: { type: String, default: 0 },
          ieTimeout: { type: String, default: 0 },
          ieSlipProfit: { type: String, default: 0 },
          ieSlipLosing: { type: String, default: 0 },
          ieVolumeMax: { type: String, default: 0 },
          ieVolumeMaxExt: { type: String, default: 0 },
        },
      ],
      default: [],
    },
    managerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "whiteLabel",
    },
    managerType: {
      type: String,
      default: "real",
    },
    minimumDepositeLimit: { type: Number, default: 200 },
    range: {
      rangeStart: {
        type: Number,
        required: true,
      },
      rangeEnd: {
        type: Number,
        required: true,
      },
    },
    spread: { type: Number, default: 0 },
    commission: { type: Number, default: 0 },
    description: {
      type: String,
      default: "Most popular! A great account for all types of traders",
    },
    status: { type: Boolean, default: true },
    isPopular: { type: Boolean, default: false },
    isDefault: { type: Boolean, default: false },
    sortedPosition: { type: Number, default: 1 },
    bookTypeB : {type : Boolean,default : true},
    linkedGroupIds: {
      type: [{ type: mongoose.Types.ObjectId, ref: "forexGroups" }],
      default: [],
    },
    linkedGroups: { type: [String], default: [] },
  },
  {
    collection: "forexGroups",
  }
);

groupSchema.index({ whiteLabel: 1, group: 1, managerId: 1 }, { unique: true });

export default mongoose.model("forexGroups", groupSchema);
